domain: js-api-entity.wex
git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  name: js-api-entity
  type: javascript-package
  version: 2.0.1
wex:
  migration: 1
  version: 6.0.139
